name: Deploy to s3
description: deploy static site to aws s3
inputs:
  bucket:
    description: s3 bucket name
    required: true
  bucket-region:
    description: aws bucket-region
    required: false
    default: eu-central-1
  dist-folder:
    description: the folder to Upload
    required: true
runs:
  using: "node16"
  main: "main.js"